Update numpy float convention
MTH5 notebooks failing on python >=3.9 due to:
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead
- removed `np.float_` reference, float64 was already there